config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pictures, except: [:destroy]
  resources :home, only: [:index]
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :basic_http_auth

  def index
    @pictures = Picture.order(:created_at)
    if params[:query]
      @pictures = @pictures.where("title ilike ? OR description ilike ?",
                                  "%#{params[:query]}%", "%#{params[:query]}%")
    end
  end

  private

  def basic_http_auth
    return if Rails.env == 'development'
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['PUBLIC_USERNAME'] && password == ENV['PUBLIC_PASSWORD']
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_action :set_picture, only: [:edit, :update]
  before_action :basic_http_auth

  def index
    @pictures = Picture.order(:created_at)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to new_picture_url, notice: "Picture added with success"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @picture.update_attributes(picture_params)
    redirect_to pictures_path
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :description, :image)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def basic_http_auth
    return if Rails.env == 'development'
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['USERNAME'] && password == ENV['PASSWORD']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/home/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Casamento Mariana e Simão</h1>
    <p class="lead text-muted">Podem ver página a página ou pesquisar.</p>
    <%= form_tag root_path, method: :get, class: "form-inline" do %>
      <%= text_field_tag :query, params[:query],
        class: "form-control col-md-8 mb-2 mr-sm-2 mb-sm-0",
        placeholder: "Igreja, Copo de Água, Família..." %>
      <%= submit_tag "Pesquisar", class: "btn btn-primary" %>
    <% end %>
  </div>
</section>

<div class="album text-muted">
  <div class="container">
    <% if @pictures.any? %>
      <div id="lightgallery" class="row">
        <% @pictures.each do |picture| %>
          <div class="card" data-src="<%= picture.image(:original) %>">
            <img src="<%= picture.image(:medium) %>" alt="<%= [picture.title.presence, picture.description.presence].compact.join(" - ") %>" />
          </div>
        <% end %>
      </div>
    <% else %>
      <p class="text-muted">Não foram encontradas fotografias para a sua pesquisa.</p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Mariana e Simão - Fotos Casamento</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Fotos de Casamento da Mariana e do Simão">
    <meta name="author" content="Simão Belchior">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 py-4">
              <h4 class="text-white">Acerca</h4>
              <p class="text-muted">Fotografias de casamento da Mariana e do Simão.</p>
            </div>
            <div class="col-sm-4 py-4">
              <h4 class="text-white">Opções</h4>
              <ul class="list-unstyled">
                <li>
                  <%= link_to "Gerir fotografias", pictures_path %>
                </li>
                <li>
                  <%= link_to "Adicionar fotografias", new_picture_path %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark">
        <div class="container d-flex justify-content-between">
          <a href="/" class="navbar-brand">Álbum</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">
    <%= yield %>
    </main>
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>
          New to Bootstrap? <a href="../../">Visit the homepage</a> or read our
          <a href="../../getting-started/">getting started guide</a>.
        </p>
      </div>
    </footer>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_for picture, html: { multipart: true } do |f| %>
  <fieldset>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= f.label :title, "Título" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group col-md-6">
        <%= f.label :description, "Descrição" %>
        <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>
    <% if @picture.new_record? %>
      <div class="form-group">
        <%= f.label :image, class: "custom-file" do %>
          <%= f.file_field :image, class: "custom-file-input" %>
          <span class="custom-file-control"></span>
        <% end %>
      </div>
    <% else %>
      <p>
        <%= image_tag(@picture.image(:medium)) %>
      </p>
    <% end %>
  </fieldset>
  <%= f.submit "#{@picture.new_record? ? "Adicionar" : "Editar"} Fotografia",
    class: "btn btn-primary" %>
<% end %>

app/views/pictures/_header.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <% flash.each do |name, msg| %>
      <span class="alert"><%= msg %></span>
    <% end %>
    <h1 class="jumbotron-heading"><%= title %></h1>
    <p class="text-muted">
      Total de fotos no sistema: <%= Picture.count %><br />
      Última foto adicionada: <%= Picture.last.try(:image_file_name) %>
    </p>
  </div>
</section>

app/views/pictures/edit.html.erb
<%= render 'header', title: "Editar fotografia" %>

<div class="container">
  <%= render 'form', picture: @picture %>
</div>

app/views/pictures/index.html.erb
<%= render 'header', title: "Todas as fotografias" %>
<div class="container">
  <ul>
    <% @pictures.each do |p| %>
      <li>
        <%= [p.title.presence, p.description.presence].join("-") %>
        <%= p.image_file_name %>
        <%= link_to "Editar", edit_picture_path(p) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/pictures/new.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <% flash.each do |name, msg| %>
      <span class="alert"><%= msg %></span>
    <% end %>
    <h1 class="jumbotron-heading">Add more pictures</h1>
    <p class="text-muted">
      Total pictures in the system: <%= Picture.count %><br />
      Last picture added: <%= Picture.last.image_file_name %>
    </p>
  </div>
</section>
<div class="container">
  <%= form_for @picture, url: pictures_path, html: { multipart: true } do |f| %>
    <fieldset>
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :image, class: "custom-file" do %>
          <%= f.file_field :image, class: "custom-file-input" %>
          <span class="custom-file-control"></span>
        <% end %>
      </div>
    </fieldset>
    <%= f.submit "Add Picture", class: "btn btn-primary" %>
  <% end %>
</div>